Repository Mu2e/Offline, pull requests merged in 2021-06, with the labels that each got.

#467 commit to using Muse as the setup and build system
  bin/createSatelliteRelease
  buildopts
  setup.sh
Labels: build finished

#440 Calo hit reco fast
  CaloCluster/fcl/prolog.fcl
  CaloCluster/fcl/prolog_trigger.fcl
  CaloCluster/src/CaloClusterFast_module.cc
  CaloCluster/src/CaloClusterMaker_module.cc
  CaloCluster/src/CaloProtoClusterMaker_module.cc
  CaloMC/fcl/common.fcl
  CaloMC/fcl/prolog.fcl
  CaloMC/inc/CaloNoiseSimGenerator.hh
  CaloMC/inc/CaloWFExtractor.hh
  CaloMC/src/CaloDigiMaker_module.cc
  CaloMC/src/CaloNoiseSimGenerator.cc
  CaloMC/src/CaloShowerStepMaker_module.cc
  CaloMC/src/CaloWFExtractor.cc
  CaloReco/fcl/prolog.fcl
  CaloReco/fcl/prolog_trigger.fcl
  CaloReco/src/CaloHitMakerFast_module.cc
  CaloReco/src/CaloHitMaker_module.cc
  CaloReco/src/CaloRawWFProcessor.cc
  CaloReco/src/CaloRecoDigiMaker_module.cc
  CaloReco/src/FastCaloRecoDigiFromDigi_module.cc
Labels: build finished

#463 Simplified calo pusle shape utility
  ConditionsService/data/CsI-waveform-2020-02-12.root
  Mu2eUtilities/src/CaloPulseShape.cc
Labels: build finished

#469 fixed chains OffSpill + clean up
  CaloFilters/fcl/prolog_trigger.fcl
  CosmicReco/fcl/prolog_trigger.fcl
  TrkFilters/fcl/prolog_trigger.fcl
Labels: build finished

#471 remove obsolete test target
  scripts/build/SConscript
  scripts/build/bin/procs.sh
Labels: build finished

#464 mchistory
  EventGenerator/src/CeEndpoint_module.cc
  EventGenerator/test/CeEndpoint.fcl
  MCDataProducts/inc/StageParticle.hh
  MCDataProducts/src/classes.h
  MCDataProducts/src/classes_def.xml
  Mu2eG4/fcl/g4test_mustops.fcl
  Mu2eG4/inc/Mu2eG4PrimaryType.hh
  Mu2eG4/inc/SimParticlePrimaryHelper.hh
  Mu2eG4/src/Mu2eG4EventAction.cc
  Mu2eG4/src/Mu2eG4IOConfigHelper.cc
  Mu2eG4/src/Mu2eG4Inputs.cc
  Mu2eG4/src/Mu2eG4MT_module.cc
  Mu2eG4/src/Mu2eG4PerThreadStorage.cc
  Mu2eG4/src/Mu2eG4PrimaryGeneratorAction.cc
  Mu2eG4/src/Mu2eG4TrackingAction.cc
  Mu2eG4/src/SimParticlePrimaryHelper.cc
Labels: build finished

#474 Fixed calo pusle root file and remove superfluous include directives
  ConditionsService/data/CsI-waveform-2020-02-12.root
  Mu2eUtilities/src/CaloPulseShape.cc
Labels: build finished

#476 Fixed out of bound access
  CaloReco/src/CaloTemplateWFProcessor.cc
Labels: build finished

#473 Fixed initial ewm phase always being zero
  CommonMC/src/EventWindowMarkerProducer_module.cc
Labels: build pending

#477 Remove debug printouts.
  Mu2eG4/src/SimParticlePrimaryHelper.cc
Labels: build finished

#478 finishNesting only creates a new LogicalVolume if the VolumeInfo does…
  Mu2eG4/src/finishNesting.cc
Labels: build finished

#454 Add production target scanning monitor
  Analyses/src/ReadPTM_module.cc
  DataProducts/inc/VirtualDetectorId.hh
  GeometryService/inc/PTMMaker.hh
  GeometryService/src/GeometryService_service.cc
  GeometryService/src/PTMMaker.cc
  GeometryService/src/SConscript
  GeometryService/src/VirtualDetectorMaker.cc
  MCDataProducts/inc/StepInstanceName.hh
  Mu2eG4/geom/PTM.txt
  Mu2eG4/geom/geom_2021_PhaseI_PTM.txt
  Mu2eG4/geom/geom_common_current.txt
  Mu2eG4/inc/SensitiveDetectorName.hh
  Mu2eG4/inc/constructPTM.hh
  Mu2eG4/src/Mu2eWorld.cc
  Mu2eG4/src/constructPTM.cc
  PTMGeom/inc/PTM.hh
  PTMGeom/inc/PTMPWC.hh
  PTMGeom/src/PTM.cc
  PTMGeom/src/PTMPWC.cc
  PTMGeom/src/SConscript
Labels: build finished

#481 reenabled geant4 overlap checking in the tracker; removed an obsolete file
  Mu2eG4/geom/g4_userOptions.txt
  Mu2eG4/geom/tracker_v6.txt
Labels: build finished

#480 Cosmic time offset module
  CommonMC/fcl/prolog.fcl
  CommonMC/src/CosmicTimeOffset_module.cc
Labels: build finished

#479 Small fixes for mixing and resampling
  EventMixing/src/ResamplingMixer_module.cc
  Filters/src/ParticleCodeFilter_module.cc
  TrkDiag/data/TrkCaloHitPID.weights.xml
  TrkDiag/data/TrkQualCalo.weights.xml
  TrkDiag/data/TrkQualNocalo.weights.xml
  fcl/standardServices.fcl
Labels: build finished

#483 deleting G4RunManager explicitly to avoid warnings
  Mu2eG4/src/Mu2eG4_module.cc
Labels: build finished

#485 Pileup resampling
  EventGenerator/inc/ParticleGeneratorTool.hh
  EventGenerator/src/CeEndpoint_module.cc
  EventGenerator/src/DIOGenerator_tool.cc
  EventGenerator/src/MuCap1809keVGammaGenerator_tool.cc
  EventGenerator/src/MuCapDeuteronGenerator_tool.cc
  EventGenerator/src/MuCapNeutronGenerator_tool.cc
  EventGenerator/src/MuCapPhotonGenerator_tool.cc
  EventGenerator/src/MuCapProtonGenerator_tool.cc
  EventGenerator/src/MuStopProductsGun_module.cc
  EventGenerator/src/Pileup_module.cc
  EventGenerator/test/CeEndpoint.fcl
  EventGenerator/test/Pileup.fcl
  MCDataProducts/inc/ProcessCode.hh
  MCDataProducts/inc/StageParticle.hh
  MCDataProducts/src/StageParticle.cc
  Mu2eUtilities/inc/SpectrumVar.hh
  Mu2eUtilities/inc/simParticleList.hh
  Mu2eUtilities/src/simParticleList.cc
Labels: build finished

#490 Remove time maps
  CommonMC/fcl/prolog.fcl
  Compression/fcl/prolog.fcl
Labels: build failed

#487 Added module to generate ComboHits from fragments
  DAQ/fcl/prolog_trigger.fcl
  DAQ/src/SConscript
  DAQ/src/StrawHitRecoFromFragments_module.cc
  TrkHitReco/inc/StrawHitRecoUtils.hh
  TrkHitReco/src/StrawHitRecoUtils.cc
  TrkHitReco/src/StrawHitReco_module.cc
Labels: build failed

#493 Fix GenEventCounter for jobs with multiple subruns.
  EventGenerator/src/GenEventCounter_module.cc
Labels: build finished

#494 Trig flag cleanup
  CRVFilters/src/CrvCoincidenceClusterFilter_module.cc
  CaloFilters/src/CaloClusterCounterFilter_module.cc
  CaloFilters/src/CaloCosmicCalib_module.cc
  CaloFilters/src/CaloLikelihood_module.cc
  CaloFilters/src/FilterEcalMVATrigger_module.cc
  CaloFilters/src/FilterEcalMixedTrigger_module.cc
  CaloFilters/src/FilterEcalNNTrigger_module.cc
  CosmicReco/src/CosmicSeedFilter_module.cc
  RecoDataProducts/inc/TriggerFlag.hh
  RecoDataProducts/inc/TriggerInfo.hh
  RecoDataProducts/src/TriggerFlag.cc
  RecoDataProducts/src/classes.h
  RecoDataProducts/src/classes_def.xml
  Trigger/src/DigiFilter_module.cc
  Trigger/src/MergeTriggerInfo_module.cc
  Trigger/src/PrescaleEvent_module.cc
  TrkFilters/src/HelixFilter_module.cc
  TrkFilters/src/SeedFilter_module.cc
  TrkFilters/src/TimeClusterFilter_module.cc
Labels: build finished

#492 Minor updates to the magnetic field configuration
  Mu2eG4/geom/bfgeom_no_ds_v01.txt
  Mu2eG4/geom/bfgeom_no_tsu_ps_v01.txt
  Mu2eG4/geom/bfgeom_reco_v01.txt
  Mu2eG4/geom/bfgeom_v01.txt
Labels: build finished

#495 TrkAna Removal
  Analyses/src/KalRepsPrinter_module.cc
  Analyses/src/ReadTrkExt_module.cc
  Analyses/src/Reflect_module.cc
  CalPatRec/fcl/prolog.fcl
  CalPatRec/src/MergeHelixFinder_module.cc
  CalPatRec/src/MergePatRec_module.cc
  CutAndCountAnalysis/inc/CutAndCountAnalysis.hh
  CutAndCountAnalysis/inc/TrackLevelCuts.hh
  CutAndCountAnalysis/src/CutAndCountAnalysis.cc
  CutAndCountAnalysis/src/CutAndCountAnalyzer_module.cc
  CutAndCountAnalysis/src/CutAndCountFilter_module.cc
  CutAndCountAnalysis/src/SConscript
  CutAndCountAnalysis/src/TrackLevelCuts.cc
  TrkDiag/inc/CaloClusterInfoMC.hh
  TrkDiag/inc/EventInfo.hh
  TrkDiag/inc/EventWeightInfo.hh
  TrkDiag/inc/GenInfo.hh
  TrkDiag/inc/HelixInfo.hh
  TrkDiag/inc/HitCount.hh
  TrkDiag/inc/InfoMCStructHelper.hh
  TrkDiag/inc/InfoStructHelper.hh
  TrkDiag/inc/KalDiag.hh
  TrkDiag/inc/RecoQualInfo.hh
  TrkDiag/inc/TrkCaloHitInfo.hh
  TrkDiag/inc/TrkCount.hh
  TrkDiag/inc/TrkInfo.hh
  TrkDiag/inc/TrkMCTools.hh
  TrkDiag/inc/TrkPIDInfo.hh
  TrkDiag/inc/TrkQualInfo.hh
  TrkDiag/inc/TrkStrawHitInfo.hh
  TrkDiag/inc/TrkStrawHitInfoMC.hh
  TrkDiag/inc/TrkStrawMatInfo.hh
  TrkDiag/inc/helixpar.hh
  TrkDiag/src/InfoMCStructHelper.cc
  TrkDiag/src/InfoStructHelper.cc
  TrkDiag/src/KalDiag.cc
  TrkDiag/src/KalSeedToTrkQualTree_module.cc
  TrkDiag/src/ReadKalFits_module.cc
  TrkDiag/src/TimeClusterDiag_module.cc
  TrkDiag/src/TrackAnalysisReco_module.cc
  TrkDiag/src/TrackPID_module.cc
  TrkDiag/src/TrackQuality_module.cc
  TrkDiag/src/classes.h
  TrkDiag/src/classes_def.xml
Labels: build finished

#496 TrkAna Fcl Removal
  TrkDiag/fcl/TrkAnaReco.fcl
  TrkDiag/fcl/TrkAnaRecoEnsemble-Data.fcl
  TrkDiag/fcl/TrkAnaRecoEnsemble-MC.fcl
  TrkDiag/fcl/TrkAnaReco_MultipleTrkQual.fcl
  TrkDiag/fcl/TrkAnaReco_Upstream.fcl
  TrkDiag/fcl/TrkAnaReco_wTrkQualFilter.fcl
  TrkDiag/fcl/prolog.fcl
Labels: build finished

#498 Add and adjust some validation plots
  Validation/inc/ValGenParticle.hh
  Validation/inc/ValStrawGasStep.hh
  Validation/src/ValGenParticle.cc
  Validation/src/ValStrawGasStep.cc
Labels: build finished, code checks failed

#491 StrawElectronics now has calibrations covering all 20k channels instead of just 96
  .gitignore
  DataProducts/inc/StrawId.hh
  DbTables/inc/TrkDelayRStraw.hh
  DbTables/src/DbTableFactory.cc
  TrackerConditions/fcl/prolog.fcl
  TrackerConditions/inc/StrawElectronics.hh
  TrackerConditions/inc/StrawElectronicsCache.hh
  TrackerConditions/inc/StrawElectronicsMaker.hh
  TrackerConditions/inc/StrawResponse.hh
  TrackerConditions/src/StrawElectronics.cc
  TrackerConditions/src/StrawElectronicsMaker.cc
  TrackerConditions/src/StrawResponse.cc
  TrackerConditions/src/StrawResponseMaker.cc
  TrackerConfig/inc/StrawElectronicsConfig.hh
  TrackerConfig/inc/StrawResponseConfig.hh
  TrackerMC/src/StrawDigisFromStrawGasSteps_module.cc
Labels: build running

#501 Production Fixes
  Analyses/src/StoppedParticlesDumper_module.cc
  EventMixing/inc/Mu2eProductMixer.hh
  EventMixing/src/Mu2eProductMixer.cc
  Filters/src/ParticleCodeFilter_module.cc
  Mu2eG4/geom/protonAbsorber_cylindrical_v04.txt
  Mu2eG4/src/ConstructMaterials.cc
Labels: build failed

#502 Fixed bug accessing electronics tmax out of range
  TrackerConditions/src/StrawElectronics.cc
Labels: build finished

#503 Primaryfix
  CommonMC/src/FindMCPrimary_module.cc
  EventGenerator/src/CeEndpoint_module.cc
  EventGenerator/src/MuStopProductsGun_module.cc
  MCDataProducts/inc/PrimaryParticle.hh
  MCDataProducts/inc/ProcessCode.hh
  Print/src/PrimaryParticlePrinter.cc
  TrkDiag/src/HelixDiag_module.cc
  Validation/src/ValKalSeed.cc
Labels: build failed

#505 Fix MCPrimary for cosmics
  CommonMC/src/FindMCPrimary_module.cc
Labels: build finished

#504 Updated to 2D TEve event display
  TEveEventDisplay/fcl/prolog.fcl
  TEveEventDisplay/src/TEveMu2eCluster.cc
  TEveEventDisplay/src/TEveMu2eDataInterface.cc
  TEveEventDisplay/src/TEveMu2eHit.cc
  TEveEventDisplay/src/TEveMu2eMCInterface.cc
  TEveEventDisplay/src/TEveMu2eMainWindow.cc
  TEveEventDisplay/src/TEveMu2eTracker.cc
  TEveEventDisplay/src/TEveMu2e_base_classes/TEveMu2eHit.h
Labels: build finished

#499 updates to the Trigger code + small fix in CaloHitMakerFast
  CalPatRec/fcl/prolog_trigger.fcl
  CalPatRec/src/CalTimePeakFinderDiag_tool.cc
  CaloReco/src/CaloHitMakerFast_module.cc
  Mu2eUtilities/inc/TriggerResultsNavigator.hh
  Mu2eUtilities/src/TriggerResultsNavigator.cc
  Trigger/data/ExtrPosTrigMenu.config
  Trigger/data/OffSpillTrigMenu.config
  Trigger/data/OnSpillTrigMenu.config
  Trigger/python/genTriggerFcl.py
  Trigger/src/ReadTriggerInfo_module.cc
Labels: build finished

#509 Remove a module not used from anywhere.
  Filters/src/FilterOutEmptyEvents_module.cc
Labels: build finished

#508 Ionfix
  Mu2eG4/src/IonProducer_module.cc
  Mu2eG4/test/iontest.fcl
  Mu2eG4/test/iontest_g4s1.fcl
  Mu2eG4/test/iontest_g4s2.fcl
Labels: build finished

#375 Added EWT and PB Timing for calorimeter
  CaloMC/fcl/prolog.fcl
  CaloMC/src/CaloDigiMaker_module.cc
  CaloMC/src/CaloShowerROMaker_module.cc
Labels: build finished

#511 clean up
  CaloFilters/fcl/prolog_trigger.fcl
  CosmicReco/fcl/prolog_trigger.fcl
  Trigger/data/ExtrPosTrigMenu.config
  Trigger/data/OffSpillTrigMenu.config
  Trigger/data/OnSpillTrigMenu.config
  Trigger/data/allPaths.config
  Trigger/data/caloCalibCosmic/main_caloCalibCosmicFilter.fcl
  Trigger/data/cstSeed/main_cstSeedTSFilter.fcl
  Trigger/python/genTriggerFcl.py
  Trigger/src/ReadTriggerInfo_module.cc
Labels: build finished

#513 fixed calo-only sequence + clean up
  CaloFilters/fcl/prolog_trigger.fcl
  Trigger/data/OffSpillTrigMenu.config
  Trigger/data/allPaths.config
  Trigger/data/caloMVANNCE/main_caloMVANNCEEventPrescale.fcl
  Trigger/data/caloMVANNCE/main_caloMVANNCEFilter.fcl
  Trigger/python/genTriggerFcl.py
Labels: build finished

#512 changed how the digitization window is applied at the CRV
  CRVResponse/fcl/prolog_v09.fcl
  CRVResponse/fcl/visibleEnergyAdjustment.txt
  CRVResponse/src/CrvDigitizer_module.cc
  CRVResponse/src/CrvPhotonGenerator_module.cc
  CRVResponse/src/CrvSiPMChargeGenerator_module.cc
  CRVResponse/src/CrvWaveformsGenerator_module.cc
  CRVResponse/src/MakeCrvDigis.cc
  CRVResponse/src/MakeCrvRecoPulses.cc
  CRVResponse/src/MakeCrvWaveforms.cc
  MCDataProducts/inc/CrvDigiMC.hh
Labels: build finished

#510 Mu2eII_SM21: Update hatch blocks to be the sizes before de-scoping
  Mu2eG4/geom/ProductionTarget_Mu2eII_Conveyor_v01.txt
  Mu2eG4/geom/geom_Mu2eII_2020.txt
Labels: build failed
