Repository Mu2e/Offline, pull requests merged in 2021-11, with the labels that each got.

#641 organize DbService verbose settings
  DbService/src/DbEngine.cc
  DbService/src/DbReader.cc
  DbService/src/DbService_service.cc
  DbService/src/DbSql.cc
Labels: build finished

#642 reduce CRV default printing
  CRVResponse/src/CrvCoincidenceCheck_module.cc
  CRVResponse/src/CrvCoincidenceClusterFinder_module.cc
  CRVResponse/src/CrvStepsFromStepPointMCs_module.cc
  fcl/standardMessageDestinations.fcl
Labels: build finished

#644 Updated default tracker digitization window
  TrackerConditions/fcl/prolog.fcl
Labels: build finished

#646 Initializing flag
  EventMixing/inc/Mu2eProductMixer.hh
Labels: build finished

#647 Extracted no bfield
  Mu2eG4/geom/bfgeom_no_field.txt
  Mu2eG4/geom/geom_common_extracted.txt
Labels: build running

#645 Used geant4 10.7 hadronic verbosity control
  Mu2eG4/src/Mu2eG4WorkerRunManager.cc
Labels: build pending

#652 start mu2e main with banner
  Mu2e/src/SConscript
  Mu2e/src/mu2e_main.cc
Labels: build finished

#651 reduce default printing
  EventMixing/src/Mu2eProductMixer.cc
  Mu2eG4/src/Mu2eG4_module.cc
  fcl/standardMessageDestinations.fcl
Labels: build finished

#655 more prints behind verbose flags
  Filters/src/RandomPrescaleFilter_module.cc
  Mu2eG4/src/Mu2eG4MTRunManager.cc
  Mu2eG4/src/Mu2eG4MT_module.cc
Labels: build finished

#648 Update PS endcap model
  GeomPrimitives/inc/Polycone.hh
  GeomPrimitives/inc/Tube.hh
  GeomPrimitives/src/Polycone.cc
  GeomPrimitives/src/Tube.cc
  GeometryService/inc/PSEnclosureMaker.hh
  GeometryService/src/PSEnclosureMaker.cc
  Mu2eG4/geom/geom_2021_PhaseI_v02.txt
  Mu2eG4/geom/geom_common_current.txt
  Mu2eG4/geom/psEnclosure_v05.txt
  Mu2eG4/src/constructPS.cc
  Mu2eG4/src/constructPSEnclosure.cc
  Mu2eG4/src/constructVirtualDetectors.cc
  ProductionSolenoidGeom/inc/PSEnclosure.hh
  ProductionSolenoidGeom/src/PSEnclosure.cc
Labels: build finished

#658 Move stable geometry forward to current version
  Mu2eG4/geom/geom_common.txt
Labels: build finished

#657 Start pywrap
  .muse
  DbService/src/SConscript
  DbService/src/pywrap.i
  DbTables/src/SConscript
  DbTables/src/pywrap.i
  MCDataProducts/inc/GenId.hh
  MCDataProducts/inc/ProcessCode.hh
  MCDataProducts/src/SConscript
  MCDataProducts/src/pywrap.i
Labels: build finished

#656 new CRV light default print
  CRVResponse/inc/MakeCrvPhotons.hh
  CRVResponse/src/CrvPhotonGenerator_module.cc
  CRVResponse/src/MakeCrvPhotons.cc
  Validation/src/Validation_module.cc
Labels: build pending

#659 Add SimEfficiencies2 table, change SimBookkeeper prodition to use it
  DbService/data/create.sql
  DbTables/inc/SimEfficiencies2.hh
  DbTables/src/DbTableFactory.cc
  SimulationConditions/inc/SimBookkeeper.hh
  SimulationConditions/inc/SimBookkeeperCache.hh
  SimulationConditions/inc/SimBookkeeperMaker.hh
  SimulationConditions/src/SimBookkeeperCache.cc
  SimulationConditions/src/SimBookkeeperMaker.cc
Labels: build finished

#649 increased speed of Crv waveform generator
  CRVResponse/inc/MakeCrvWaveforms.hh
  CRVResponse/src/CrvCoincidenceClusterFinder_module.cc
  CRVResponse/src/CrvWaveformsGenerator_module.cc
  CRVResponse/src/MakeCrvRecoPulses.cc
  CRVResponse/src/MakeCrvWaveforms.cc
Labels: build finished

#660 FlagBkg clustering hit fix
  TrkHitReco/fcl/prolog.fcl
  TrkHitReco/src/FlagBkgHits_module.cc
  TrkReco/inc/BkgClusterer.hh
  TrkReco/inc/ScanClusterer.hh
  TrkReco/inc/TNTClusterer.hh
  TrkReco/src/ScanClusterer.cc
  TrkReco/src/TNTClusterer.cc
Labels: build finished

#661 fix some references to null pointers
  Mu2eG4/src/constructMBS.cc
Labels: build finished

#663 start support for TH2
  Validation/inc/TValCompare.hh
  Validation/inc/TValHist2.hh
  Validation/root/TValCompare.cc
  Validation/root/TValHist2.cc
  Validation/root/classes.h
  Validation/root/classes_def.xml
Labels: build finished

#665 fixed the cstSeed trigger sequence
  CosmicReco/fcl/prolog_trigger.fcl
  CosmicReco/src/CosmicTrackFinder_module.cc
Labels: build finished

#650 Changed Crv digi/binary/fragment converters and CrvDigi generator
  .muse
  CRVResponse/inc/MakeCrvDigis.hh
  CRVResponse/src/CrvDigitizer_module.cc
  CRVResponse/src/MakeCrvDigis.cc
  DAQ/src/ArtBinaryPacketsFromDigis_module.cc
  DAQ/src/CrvDigisFromFragments_module.cc
  DAQ/test/generateCrvDigiFromFragment.fcl
  EventDisplay/src/dict_classes/ComponentInfo.h
  RecoDataProducts/inc/CrvDigi.hh
Labels: build finished

#664 Added cstTimeCluster to Offspill and ExtrPos menu
  CosmicReco/fcl/prolog_trigger.fcl
  Trigger/data/ExtrPosTrigMenu.config
  Trigger/data/OffSpillTrigMenu.config
  Trigger/data/cstSeed/main_cstSeedEventPrescale.fcl
  Trigger/data/cstTimeCluster/main_cstTimeClusterEventPrescale.fcl
  Trigger/data/cstTimeCluster/main_cstTimeClusterSDCountFilter.fcl
  Trigger/data/cstTimeCluster/main_cstTimeClusterTCFilter.fcl
Labels: build pending
