Repository Mu2e/Offline, pull requests merged in 2021-04, with the labels that each got.

#381 Mu2ekk
  DataProducts/inc/StrawEnd.hh
  EventDisplay/src/DataInterface.cc
  EventDisplay/src/SConscript
  Filters/src/SConscript
  JobConfig/digitize/CeEndpoint.fcl
  JobConfig/digitize/NoPrimary.fcl
  JobConfig/reco/prolog.fcl
  Mu2eKinKal/fcl/SeedTest.fcl
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/KKBField.hh
  Mu2eKinKal/inc/KKCaloHit.hh
  Mu2eKinKal/inc/KKFileFinder.hh
  Mu2eKinKal/inc/KKPanelHit.hh
  Mu2eKinKal/inc/KKStrawHit.hh
  Mu2eKinKal/inc/KKStrawHitUpdater.hh
  Mu2eKinKal/src/KKBField.cc
  Mu2eKinKal/src/KKStrawHitUpdater.cc
  Mu2eKinKal/src/LoopHelixFit_module.cc
  Mu2eKinKal/src/SConscript
  Print/src/KalSeedPrinter.cc
  Print/src/SConscript
  RecoDataProducts/inc/HitT0.hh
  RecoDataProducts/inc/KKLoopHelix.hh
  RecoDataProducts/inc/KalSeed.hh
  RecoDataProducts/inc/KalSegment.hh
  RecoDataProducts/inc/RobustHelix.hh
  RecoDataProducts/inc/TrkFitFlag.hh
  RecoDataProducts/inc/TrkStrawHitSeed.hh
  RecoDataProducts/src/ComboHit.cc
  RecoDataProducts/src/KalSeed.cc
  RecoDataProducts/src/KalSegment.cc
  RecoDataProducts/src/SConscript
  RecoDataProducts/src/TrackSummary.cc
  RecoDataProducts/src/classes.h
  RecoDataProducts/src/classes_def.xml
  TEveEventDisplay/src/SConscript
  TEveEventDisplay/src/TEveMu2eCustomHelix.cc
  TrackerConditions/inc/StrawResponse.hh
  TrkDiag/src/InfoStructHelper.cc
  TrkDiag/src/SConscript
  TrkDiag/src/TrackQuality_module.cc
  TrkDiag/src/TrkRecoDiag_module.cc
  TrkFilters/src/SConscript
  TrkFilters/src/SeedFilter_module.cc
  TrkHitReco/src/StrawHitReco_module.cc
  TrkPatRec/src/KalFinalFit_module.cc
  TrkPatRec/src/KalSeedFit_module.cc
  TrkReco/inc/TrkUtilities.hh
  TrkReco/src/KalFit.cc
  TrkReco/src/SConscript
  TrkReco/src/TrkUtilities.cc
  Validation/fcl/reco.fcl
  Validation/src/SConscript
  scripts/build/python/sconstruct_helper.py
  setup.sh
Labels: build finished

#399 add KinKal to Muse setup
  .muse
Labels: build finished

#378 Updated tracker digitization to use window end time set in conditions
  CommonMC/src/EventWindowMarkerProducer_module.cc
  CommonMC/src/GenerateCosmicTimes_module.cc
  CommonMC/src/SConscript
  DAQConditions/fcl/prolog.fcl
  DAQConditions/inc/EventTiming.hh
  DAQConditions/inc/EventTimingCache.hh
  DAQConditions/inc/EventTimingMaker.hh
  DAQConditions/src/EventTiming.cc
  DAQConditions/src/EventTimingMaker.cc
  DAQConditions/src/SConscript
  DAQConfig/inc/EventTimingConfig.hh
  ProditionsService/fcl/prolog.fcl
  ProditionsService/inc/ProditionsService.hh
  ProditionsService/src/ProditionsService_service.cc
  ProditionsService/src/SConscript
  TrackerConditions/fcl/prolog.fcl
  TrackerConditions/inc/StrawElectronics.hh
  TrackerConditions/inc/StrawElectronicsCache.hh
  TrackerConditions/inc/StrawElectronicsMaker.hh
  TrackerConditions/src/StrawElectronics.cc
  TrackerConditions/src/StrawElectronicsMaker.cc
  TrackerConfig/inc/StrawElectronicsConfig.hh
  TrackerMC/src/StrawDigisFromStrawGasSteps_module.cc
Labels: build finished

#400 switch from getenv to data file lookup
  EventDisplay/src/EventDisplayFrame.cc
Labels: build finished

#404 remove unused file with a space in the name
  Mu2eUtilities/inc/ BuildMatrixSums.hh
Labels: build finished

#401 rework bin scripts
  bin/browse
  bin/newPackage
  bin/overlapCheck.sh
Labels: build finished

#405 restore dependency lists in Muse build
  scripts/build/SConscript
  scripts/build/bin/procs.sh
Labels: build finished

#403 Mu2ekk2
  .muse
  CommonMC/src/SelectRecoMC_module.cc
  JobConfig/reco/prolog.fcl
  Mu2eKinKal/fcl/SeedTest.fcl
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/KKBField.hh
  Mu2eKinKal/inc/KKCaloHit.hh
  Mu2eKinKal/src/LoopHelixFit_module.cc
  RecoDataProducts/inc/KalSeed.hh
  RecoDataProducts/inc/TrkFitFlag.hh
  RecoDataProducts/src/TrkFitFlag.cc
  TrkDiag/inc/TrkInfo.hh
  TrkDiag/src/InfoStructHelper.cc
  TrkDiag/src/KalDiag.cc
  TrkPatRec/src/KalFinalFit_module.cc
  TrkPatRec/src/KalSeedFit_module.cc
  Validation/fcl/reco.fcl
  setup.sh
Labels: build finished

#377 Updates to DAQ code for new version of mu2e_artdaq_core and pcie_linux_kernel_module
  DAQ/fcl/prolog_trigger.fcl
  DAQ/src/ArtBinaryPacketsFromDigis_module.cc
  DAQ/src/CaloDAQUtilities.cc
  DAQ/src/CaloHitsFromFragments_module.cc
  DAQ/src/CaloRecoFromFragments_module.cc
  DAQ/src/CrvDigisFromFragments_module.cc
  DAQ/src/StrawAndCaloDigisFromFragments_module.cc
  DAQ/src/StrawRecoFromFragments_module.cc
  DAQ/test/generateDigiFromFragment.fcl
  setup.sh
  ups_install/install.sh
  ups_install/installTableFile.sh
Labels: build finished

#407 update to p003 for update of mu2e_artdaq_core
  .muse
Labels: build finished

#406 Edit TrackerAlignment README, also test new CI scripts
  TrackerAlignment/README.md
Labels: build pending

#402 Volume mixing
  CommonMC/src/SConscript
  CommonMC/src/StoppedParticlesFinder_module.cc
  EventMixing/fcl/testVolumeMixing.fcl
  EventMixing/inc/Mu2eProductMixer.hh
  EventMixing/src/MixBackgroundFrames_module.cc
  EventMixing/src/Mu2eProductMixer.cc
  EventMixing/src/ResamplingMixer_module.cc
  JobConfig/beam/DS-resampler.fcl
  MCDataProducts/inc/PhysicalVolumeInfo.hh
  MCDataProducts/inc/PhysicalVolumeInfoMultiCollection.hh
  MCDataProducts/src/PhysicalVolumeInfo.cc
  MCDataProducts/src/PhysicalVolumeInfoMultiCollection.cc
  Mu2eG4/fcl/g4test_mix1MT.fcl
  Mu2eG4/fcl/g4test_mix1ST.fcl
  Mu2eG4/inc/Mu2eG4Config.hh
  Mu2eG4/inc/Mu2eG4Inputs.hh
  Mu2eG4/inc/writePhysicalVolumes.hh
  Mu2eG4/src/Mu2eG4IOConfigHelper.cc
  Mu2eG4/src/Mu2eG4Inputs.cc
  Mu2eG4/src/Mu2eG4MT_module.cc
  Mu2eG4/src/Mu2eG4_module.cc
  Mu2eG4/src/writePhysicalVolumes.cc
Labels: build finished

#411 StoppedParticlesFinder: fix a bug introduced in the recent commit 4c9…
  CommonMC/src/StoppedParticlesFinder_module.cc
Labels: build finished

#408 Updated time wrapping and implemented the EventWindow in CRV MC and Reco
  Analyses/src/CosmicAnalysis_module.cc
  CRVAnalysis/src/CRVAnalysis.cc
  CRVResponse/fcl/prolog.fcl
  CRVResponse/fcl/prolog_v09.fcl
  CRVResponse/inc/MakeCrvPhotons.hh
  CRVResponse/inc/MakeCrvRecoPulses.hh
  CRVResponse/inc/MakeCrvSiPMCharges.hh
  CRVResponse/src/CRVTest_module.cc
  CRVResponse/src/CrvCoincidenceCheck_module.cc
  CRVResponse/src/CrvDigitizer_module.cc
  CRVResponse/src/CrvPhotonGenerator_module.cc
  CRVResponse/src/CrvPlot_module.cc
  CRVResponse/src/CrvRecoPulsesFinder_module.cc
  CRVResponse/src/CrvSiPMChargeGenerator_module.cc
  CRVResponse/src/CrvStepsFromStepPointMCs_module.cc
  CRVResponse/src/MakeCrvPhotons.cc
  CRVResponse/src/MakeCrvRecoPulses.cc
  CRVResponse/src/MakeCrvSiPMCharges.cc
  CRVResponse/src/SConscript
  CRVResponse/standalone/wls/src/WLSSteppingAction.cc
  EventDisplay/fcl/EventDisplay.fcl
  EventDisplay/src/ContentSelector.cc
  EventDisplay/src/ContentSelector.h
  EventDisplay/src/DataInterface.cc
  EventDisplay/src/EventDisplayFrame.cc
  EventDisplay/src/EventDisplayFrame.h
  EventDisplay/src/TrackColorSelector.cc
  EventDisplay/src/dict_classes/ComponentInfo.h
  JobConfig/common/geom_common_phase1.txt
  Mu2eG4/geom/crv_counters_v08.txt
  Mu2eG4/geom/geom_2019_PhaseI.txt
  Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt
  Mu2eG4/geom/geom_2021_PhaseI.txt
  Mu2eG4/geom/geom_MARS_2019.txt
  Mu2eG4/geom/geom_common_haymanLowerDensity.txt
  Mu2eG4/geom/geom_common_hayman_v2.txt
  Print/inc/CrvRecoPulsePrinter.hh
  RecoDataProducts/inc/CrvRecoPulse.hh
  RecoDataProducts/inc/CrvRecoPulseCollection.hh
  RecoDataProducts/inc/CrvRecoPulseFlags.hh
  RecoDataProducts/src/classes.h
  RecoDataProducts/src/classes_def.xml
  TEveEventDisplay/src/TEveMu2e_base_classes/TEveMu2eCRVEvent.h
  TEveEventDisplay/src/dict_classes/Collection_Filler.h
  TEveEventDisplay/src/dict_classes/Data_Collections.h
  Validation/inc/ValCrvRecoPulse.hh
Labels: build finished

#413 using newer Geant4 verbosity controls etc.
  Mu2eG4/src/Mu2eG4MTRunManager.cc
  Mu2eG4/src/Mu2eG4_module.cc
  Mu2eG4/src/SConscript
Labels: build finished

#417 Add MDC2020 unit tests
  Validation/test/ceDigi.fcl
  Validation/test/ceMix.fcl
  Validation/test/ceSteps.fcl
  Validation/test/muSteps.fcl
Labels: build finished

#416 fix bug in text override
  DbService/src/DbEngine.cc
Labels: build finished

#418 temporary fix due to PR398 + added TriggerInfoMerger module (with config tested) + clean up
  CaloFilters/fcl/prolog_trigger.fcl
  CaloReco/fcl/prolog_trigger.fcl
  Trigger/data/caloCalibCosmic/main_caloCalibCosmicPrescale.fcl
  Trigger/data/caloLHCE/main_caloLHCEPrescale.fcl
  Trigger/data/caloMVACE/main_caloMVACEPrescale.fcl
  Trigger/data/caloMVAMixedCE/main_caloMVACEPrescale.fcl
  Trigger/data/caloPhoton/main_caloPhotonPrescale.fcl
  Trigger/data/cprCosmicSeedDeM/main_cprCosmicSeedDeMPrescale.fcl
  Trigger/data/cprCosmicSeedDeP/main_cprCosmicSeedDePPrescale.fcl
  Trigger/data/cprLowPSeedDeM/main_cprLowPSeedDeMPrescale.fcl
  Trigger/data/cprLowPSeedDeP/main_cprLowPSeedDePPrescale.fcl
  Trigger/data/cprSeedDeM/main_cprSeedDeMPrescale.fcl
  Trigger/data/cprSeedDeP/main_cprSeedDePPrescale.fcl
  Trigger/data/largeCDCount/main_largeCDCountPrescale.fcl
  Trigger/data/largeSDCount/main_largeSDCountPrescale.fcl
  Trigger/data/minimumbiasCDCount/main_minimumbiasCDCountPrescale.fcl
  Trigger/data/minimumbiasSDCount/main_minimumbiasSDCountPrescale.fcl
  Trigger/data/tprCosmicSeedDeM/main_tprCosmicSeedDeMPrescale.fcl
  Trigger/data/tprCosmicSeedDeP/main_tprCosmicSeedDePPrescale.fcl
  Trigger/data/tprHelixCalibIPADeM/main_tprHelixCalibIPADeMPrescale.fcl
  Trigger/data/tprHelixIPADeM/main_tprHelixIPADeMPrescale.fcl
  Trigger/data/tprLowPSeedDeM/main_tprLowPSeedDeMPrescale.fcl
  Trigger/data/tprLowPSeedDeP/main_tprLowPSeedDePPrescale.fcl
  Trigger/data/tprSeedDeM/main_tprSeedDeMPrescale.fcl
  Trigger/data/tprSeedDeP/main_tprSeedDePPrescale.fcl
  Trigger/data/unbiased/main_unbiasedEventPrescale.fcl
  Trigger/data/unbiased/main_unbiasedPrescale.fcl
  Trigger/fcl/prolog_trigger.fcl
  Trigger/python/genTriggerFcl.py
  Trigger/src/MergeTriggerInfo_module.cc
  TrkFilters/fcl/prolog_trigger.fcl
Labels: build finished

#414 Update to doc888 v13 geometry
  GeometryService/src/TrackerMaker.cc
  JobConfig/mixing/prolog.fcl
  Mu2eG4/geom/geom_2021_PhaseI.txt
  Mu2eG4/geom/tracker_v6.txt
  Print/fcl/print.fcl
  Print/inc/ProductPrinter.hh
  TrkHitReco/src/StrawHitReco_module.cc
Labels: build finished

#421 fixed names of the module instance
  CaloReco/fcl/prolog_trigger.fcl
  DAQ/fcl/prolog_trigger.fcl
Labels: build finished

#424 changed name of the input caloHit collection in CaloCluster
  CaloCluster/fcl/prolog_trigger.fcl
Labels: build finished

#422 Remove trigger prolog from cesimreco configuration, as it is overwrit…
  Validation/fcl/ceSimReco.fcl
Labels: build pending

#420 VolumeInfo is supposed to be optional in product mixinig
  EventMixing/inc/Mu2eProductMixer.hh
  EventMixing/src/Mu2eProductMixer.cc
Labels: build finished

#425 move MVA xml to data dir
  CosmicReco/fcl/prolog.fcl
  TrkDiag/fcl/prolog.fcl
  TrkPatRec/data/HelixHitMVA.weights.xml
  TrkPatRec/data/HelixNonStereoHitMVA.weights.xml
  TrkPatRec/data/HelixStereoHitMVA.weights.xml
  TrkPatRec/data/TimeCluster.weights.xml
  TrkPatRec/data/TimeCluster3.weights.xml
  TrkPatRec/data/TimeClusterCalo.weights.xml
  TrkPatRec/fcl/prolog.fcl
Labels: build finished

#419 Used AntiLeakRegistry for rotation matrices and nullptr for identity rotations
  Mu2eG4/src/constructDS.cc
  Mu2eG4/src/constructExternalShielding.cc
  Mu2eG4/src/constructHall.cc
  Mu2eG4/src/constructHaymanRings.cc
  Mu2eG4/src/constructPSShield.cc
  Mu2eG4/src/constructProtonAbsorber.cc
  Mu2eG4/src/constructSTM.cc
  Mu2eG4/src/constructSaddles.cc
  Mu2eG4/src/constructTS.cc
  Mu2eG4/src/constructTargetPS.cc
Labels: build finished

#428 Remove unnecessary stanza
  JobConfig/mixing/prolog.fcl
Labels: build finished

#432 Calo hot fix
  CaloMC/src/CaloDigiMaker_module.cc
Labels: build failed

#433 rename muSteps, update mixing fcl
  Validation/test/ceMix.fcl
  Validation/test/muDauSteps.fcl
Labels: build failed
