Repository Mu2e/Offline, pull requests merged in 2022-02, with the labels that each got.

#698 Making the code compatible with Geant4 v11
  MCDataProducts/inc/ProcessCode.hh
  Mu2eG4/inc/PhysicsProcessInfo.hh
  Mu2eG4/src/ConstructMaterials.cc
  Mu2eG4/src/Mu2eG4MinDEDXPhysicsConstructor.cc
  Mu2eG4/src/Mu2eG4TrackingAction.cc
  Mu2eG4/src/PhysicsProcessInfo.cc
  Mu2eG4/src/SConscript
Labels: build finished

#701 IOV updates
  DbTables/src/DbIoV.cc
Labels: build finished

#700 fixed issue: https://github.com/art-framework-suite/art/issues/112
  Mu2eG4/inc/MTMasterThread.hh
  Mu2eG4/inc/Mu2eG4ActionInitialization.hh
  Mu2eG4/inc/Mu2eG4EventAction.hh
  Mu2eG4/inc/Mu2eG4MTRunManager.hh
  Mu2eG4/inc/Mu2eG4MasterRunAction.hh
  Mu2eG4/inc/Mu2eG4PerThreadStorage.hh
  Mu2eG4/inc/Mu2eG4PrimaryGeneratorAction.hh
  Mu2eG4/inc/Mu2eG4RunAction.hh
  Mu2eG4/inc/Mu2eG4SensitiveDetector.hh
  Mu2eG4/inc/Mu2eG4StackingAction.hh
  Mu2eG4/inc/Mu2eG4SteppingAction.hh
  Mu2eG4/src/ConstructMaterials.cc
  Mu2eG4/src/MTMasterThread.cc
Labels: build finished

#683 Update to KinKal v1.1.3
  .muse
  BFieldGeom/inc/BFieldManager.hh
  BFieldGeom/src/BFieldManager.cc
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/KKBField.hh
  Mu2eKinKal/inc/KKCaloHit.hh
  Mu2eKinKal/inc/KKFit.hh
  Mu2eKinKal/inc/KKFitSettings.hh
  Mu2eKinKal/inc/KKPanelHit.hh
  Mu2eKinKal/inc/KKStrawHit.hh
  Mu2eKinKal/inc/KKStrawHitUpdater.hh
  Mu2eKinKal/inc/KKTrack.hh
  Mu2eKinKal/src/KKBField.cc
  Mu2eKinKal/src/KKFitSettings.cc
  Mu2eKinKal/src/KKFitUtilities.cc
  Mu2eKinKal/src/KinematicLineFit_module.cc
  Mu2eKinKal/src/LoopHelixFit_module.cc
  RecoDataProducts/src/classes_def.xml
  TrkReco/inc/HitAmbigResolver.hh
  TrkReco/src/HitAmbigResolver.cc
Labels: build finished

#704 Fix to ranges and associated tests for calo cluster adding
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/KKFit.hh
  Mu2eKinKal/src/LoopHelixFit_module.cc
Labels: build finished

#705 Add protections against poor fits when adding CaloCluster hits
  Mu2eKinKal/inc/KKFit.hh
  Mu2eKinKal/src/LoopHelixFit_module.cc
Labels: build finished

#707 add time selection options
  DbService/inc/DbTool.hh
  DbService/src/DbTool.cc
Labels: build finished

#697 added mother volumes around CRV sectors
  Mu2eG4/src/Mu2eWorld.cc
  Mu2eG4/src/constructCRV.cc
Labels: build finished

#710 proper IOV subtraction
  DbService/src/DbEngine.cc
Labels: build finished

#713 Cleanup 220215
  DbService/inc/DbEngine.hh
  DbService/src/DbEngine.cc
  DbService/src/DbServiceTest_module.cc
Labels: build finished

#712 Increase range of PBI
  EventMixing/src/ProtonBunchIntensityFlat_module.cc
  EventMixing/src/ProtonBunchIntensityLogNormal_module.cc
  MCDataProducts/inc/ProtonBunchIntensity.hh
  Sources/src/PBISequence_source.cc
Labels: build finished

#714 Update UPS product version to use new 'd' version.
  ups_install/install.sh
  ups_install/installTableFile.sh
Labels: build running

#716 Update installTableFile.sh
  ups_install/installTableFile.sh
Labels: build finished

#715 Multiiov 220217
  DbService/src/DbServiceTest_module.cc
  DbService/src/DbTool.cc
  DbTables/src/DbUtil.cc
Labels: build finished

#717 add option to match to the nearest calibration
  DbService/inc/DbEngine.hh
  DbService/inc/DbService.hh
  DbService/src/DbEngine.cc
  DbService/src/DbService_service.cc
Labels: build finished

#711 added CrvCoincidenceFinder as replacement for CrvCoincidenceCheck/CrvCoincidenceClusterFinder
  CRVResponse/fcl/prolog.fcl
  CRVResponse/fcl/prolog_v10.fcl
  CRVResponse/src/CrvCoincidenceFinder_module.cc
Labels: build finished

#719 improve Proditions cache
  Analyses/src/SConscript
  CRVResponse/src/SConscript
  CaloMC/src/SConscript
  CommonMC/src/SConscript
  CosmicReco/src/SConscript
  DAQ/src/SConscript
  DbService/test/DbServiceTest_module.cc
  EventMixing/src/SConscript
  Filters/src/SConscript
  Mu2eInterfaces/inc/ProditionsCache.hh
  Mu2eKinKal/src/SConscript
  ParticleID/src/SConscript
  ProditionsService/fcl/proditionsTest.fcl
  ProditionsService/test/ProditionsTest_module.cc
  TrackerMC/src/SConscript
  TrkDiag/src/SConscript
  TrkHitReco/src/SConscript
  TrkPatRec/src/SConscript
Labels: build finished

#720 Refactor IoV code
  DbService/fcl/dbServiceTest.fcl
  DbService/inc/DbEngine.hh
  DbService/inc/DbValTool.hh
  DbService/src/DbEngine.cc
  DbService/src/DbServiceTest_module.cc
  DbService/src/DbValTool.cc
  DbService/test/dbServiceTest.fcl
  DbTables/inc/DbSet.hh
  DbTables/src/DbSet.cc
  ProditionsService/src/ProditionsTest_module.cc
  ProditionsService/test/proditionsTest.fcl
Labels: build finished

#721 install database table cache purge
  DbService/inc/DbEngine.hh
  DbService/inc/DbService.hh
  DbService/src/DbEngine.cc
  DbService/src/DbService_service.cc
  DbTables/inc/DbCache.hh
  DbTables/src/DbCache.cc
Labels: build finished

#723 check for overlaps in override tables
  DbService/src/DbEngine.cc
Labels: build finished

#718 fixed calo time offset and improved cpr peak finder
  CalPatRec/fcl/prolog.fcl
  CalPatRec/src/CalTimePeakFinder_module.cc
Labels: build pending

#724 write multiple IoV on a TABLE line
  DbTables/src/DbUtil.cc
Labels: build finished
