Repository Mu2e/Offline, pull requests merged in 2024-04, with the labels that each got.

#1229 Revert type change
  MCDataProducts/inc/MCRelationship.hh
Labels: build finished

#1230 add trk align sim and crv tables
  DbService/data/create.sql
Labels: build finished

#1231 compressPDGCodeHisto() tweak
  Mu2eUtilities/inc/compressPdgId.hh
  Mu2eUtilities/src/compressPdgId.cc
Labels: build finished

#1233 Add module to merge KalSeed collections
  RecoDataProducts/inc/KalSeed.hh
  RecoDataProducts/src/classes_def.xml
  TrkReco/src/MergeKalSeeds_module.cc
  TrkReco/test/TestMergeKalSeeds.fcl
Labels: build finished

#1232 Enable AlignedTrackerSim db
  TrackerConditions/fcl/prolog.fcl
Labels: build finished

#1234 clean up of deprecated fcl files + fixed one bug in CalHelixFinderAlg
  CalPatRec/inc/CalHelixFinderData.hh
  CaloFilters/fcl/runCaloOnlyFilter.fcl
  TrkFilters/fcl/ReadDigis.fcl
  TrkFilters/fcl/ReadDigisCalo.fcl
  TrkReco/fcl/prolog_trigger.fcl
Labels: build pending

#1236 make ptr check more general
  Validation/src/ValStepPointMC.cc
Labels: build finished

#1235 Add protection against tracks with too few usable hits
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/HelixFit_module.hh
  Mu2eKinKal/inc/KKFit.hh
  Mu2eKinKal/inc/KKFitSettings.hh
  Mu2eKinKal/inc/KKStrawHit.hh
Labels: build pending

#1241 Remove dead straws even in offspill
  TrkDiag/src/ComboHitDiag_module.cc
  TrkDiag/src/StrawHitDiag_module.cc
  TrkHitReco/src/CombineStrawHits_module.cc
Labels: build failed

#1243 add mu+'s
  Mu2eG4/src/Mu2eG4TrackingAction.cc
Labels: build failed

#1244 enabling g4studyMT
  Mu2eG4/g4study/g4studyMT.fcl
  Mu2eG4/src/Mu2eG4MTRunManager.cc
Labels: build finished

#1246 Trivial change that will be merged to force CI on another PR.
  README.md
Labels: build running

#1238 changed the structure of the Helix filter + added a data member in the HelixSeed
  CalPatRec/fcl/prolog.fcl
  CalPatRec/inc/CalHelixFinder_module.hh
  CalPatRec/src/CalHelixFinder_module.cc
  CaloFilters/src/CaloLikelihood_module.cc
  CaloFilters/src/FilterEcalNNTrigger_module.cc
  Mu2eUtilities/inc/HelixTool.hh
  Mu2eUtilities/src/HelixTool.cc
  RecoDataProducts/inc/HelixRecoDir.hh
  RecoDataProducts/inc/HelixSeed.hh
  RecoDataProducts/inc/TriggerInfo.hh
  RecoDataProducts/src/classes.h
  RecoDataProducts/src/classes_def.xml
  Trigger/src/ReadTriggerInfo_module.cc
  TrkFilters/CMakeLists.txt
  TrkFilters/src/HelixFilter_module.cc
  TrkFilters/src/KalSeedFilter_module.cc
  TrkFilters/src/SeedFilter_module.cc
  TrkFilters/src/TimeClusterFilter_module.cc
  TrkPatRec/fcl/prolog.fcl
  TrkPatRec/src/RobustHelixFinder_module.cc
Labels: build pending
