Repository Mu2e/Offline, pull requests merged in 2025-05, with the labels that each got.

#1402 straw digis from artdaq fragments
  DAQ/CMakeLists.txt
  DAQ/doc/DAQ.org
  DAQ/fcl/prolog.fcl
  DAQ/src/StrawDigisFromArtdaqFragments_module.cc
  DAQ/test/make_straw_digis.fcl
  DAQ/test/print_tracker_digi.fcl
  RecoDataProducts/inc/StrawDigiFlag.hh
Labels: build pending

#1456 new CRV geometry and prolog
  CRVConditions/data/calib_nominal_v10.txt
  CRVConditions/data/calib_nominal_v10_perfect.txt
  CRVConditions/data/nominal_v10.txt
  CRVConditions/data/photonyield_nominal_v10.txt
  CRVConditions/data/photonyield_nominal_v10_perfect.txt
  CRVConditions/data/status_nominal_v10.txt
  CRVConditions/data/status_nominal_v10_perfect.txt
  CRVConditions/test/channelMap.py
  CRVConditions/test/randomDeadChannels.py
  CRVConditions/test/randomPhotonYieldDeviation.py
  CRVReco/fcl/prolog_v12.fcl
  CRVResponse/fcl/prolog_v12.fcl
  EventDisplay/src/DataInterface.cc
  GeometryService/inc/STMMaker.hh
  GeometryService/src/STMMaker.cc
  Mu2eG4/geom/ExtShieldUpstream_v06.txt
  Mu2eG4/geom/STM_v08.txt
  Mu2eG4/geom/crv_counters_v10.txt
  Mu2eG4/geom/geom_common_crv_v10.txt
  Mu2eG4/src/constructSTM.cc
Labels: build pending

#1477 moved the borated polyethylene back to its original position
  Mu2eG4/geom/ExtShieldUpstream_v06.txt
Labels: build finished

#1479 Update accept-reject filter module
  Filters/src/WeightSamplingFilter_module.cc
Labels: build finished

#1481 fix cmake build
  Filters/CMakeLists.txt
Labels: build finished

#1488 Intersection fixes
  .gitignore
  DataProducts/CMakeLists.txt
  DataProducts/inc/StrawEnd.hh
  DataProducts/src/StrawEnd.cc
  KinKalGeom/inc/DetectorSolenoid.hh
  KinKalGeom/src/DetectorSolenoid.cc
  KinKalGeom/src/Tracker.cc
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/ExtrapolateIPA.hh
  Mu2eKinKal/inc/ExtrapolateST.hh
  Mu2eKinKal/inc/ExtrapolateTCRV.hh
  Mu2eKinKal/inc/ExtrapolateToZ.hh
  Mu2eKinKal/inc/KKShellXing.hh
  Mu2eKinKal/src/CentralHelixFit_module.cc
  Mu2eKinKal/src/KinematicLineFit_module.cc
  Mu2eKinKal/src/LoopHelixFit_module.cc
  Print/src/KalSeedPrinter.cc
  RecoDataProducts/inc/CosmicTrack.hh
Labels: build finished

#1489 p077 for kinkal 3.2.0
  .muse
Labels: build failed

#1484 Beam dump move
  GeometryService/src/ExtMonFNALFilterMaker.cc
  GeometryService/src/ProtonBeamDumpMaker.cc
  Mu2eG4/geom/extmon_filter_absolute.txt
  Mu2eG4/geom/extmon_filter_relative.txt
  Mu2eG4/geom/extmon_fnal_v02.txt
  Mu2eG4/geom/protonBeamDump_v02.txt
  Mu2eG4/geom/protonBeamDump_v03.txt
  Mu2eG4/src/constructExtMonFNALBuilding.cc
  Mu2eG4/src/constructProtonBeamDump.cc
  ProtonBeamDumpGeom/inc/ProtonBeamDump.hh
  ProtonBeamDumpGeom/src/ProtonBeamDump.cc
Labels: build finished

#1492 p078
  .muse
Labels: build finished

#1490 Update CalCosmicEnergyCalib.hh table length
  DbTables/inc/CalCosmicEnergyCalib.hh
Labels: build pending

#1485 Calo digis and hits from DTCEvents - and cleanup
  DAQ/CMakeLists.txt
  DAQ/inc/CaloDAQUtilities.hh
  DAQ/src/CaloDAQUtilities.cc
  DAQ/src/CaloDigisFromDTCEvents_module.cc
  DAQ/src/CaloDigisFromDataDecoders_module.cc
  DAQ/src/CaloHitsFromDTCEvents_module.cc
Labels: build pending

#1494 p079
  .muse
Labels: build finished

#1496 fit sampling consolidation
  Mu2eKinKal/inc/KKFit.hh
  Mu2eKinKal/src/CentralHelixFit_module.cc
  Mu2eKinKal/src/KinematicLineFit_module.cc
  Mu2eKinKal/src/LoopHelixFit_module.cc
  Validation/src/ValKalSeed.cc
Labels: build finished

#1495 cal archive table
  DbService/data/create.sql
Labels: build pending

#1486 Add track overlap clustering
  RecoDataProducts/inc/KalSeed.hh
  TrkDiag/CMakeLists.txt
  TrkDiag/src/TrackMatching_module.cc
  TrkDiag/src/TrackResolution_module.cc
Labels: build finished

#1497 Update track clustering to properly check each track combination
  TrkDiag/src/TrackMatching_module.cc
Labels: build finished

#1498 Add CID to CalCosmicEnergyCalibInfo
  DbTables/inc/CalCosmicEnergyCalibInfo.hh
Labels: build finished

#1500 Expand set of surfaces for straight tracks
  Validation/src/ValKalSeed.cc
Labels: build running

#1499 open interval print feature
  DbService/data/create.sql
  DbService/inc/OpenTool.hh
  DbService/src/OpenHandle.cc
  DbService/src/OpenTool.cc
  DbService/src/openTool_main.cc
Labels: build finished

#1502 Move track matching modules
  TrkDiag/CMakeLists.txt
  TrkReco/CMakeLists.txt
  TrkReco/src/TrackMatching_module.cc
  TrkReco/src/TrackResolution_module.cc
Labels: build finished

#1503 Protect NoPrimary
  MCDataProducts/inc/PrimaryParticle.hh
Labels: build finished

#1505 edit pion filter
  EventGenerator/fcl/prolog.fcl
  EventGenerator/src/PionFilter_module.cc
Labels: build finished

#1506 DetStepFilter fix
  Filters/src/DetectorStepFilter_module.cc
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/src/LoopHelixFit_module.cc
Labels: build finished
