Repository Mu2e/Offline, pull requests merged in 2025-03, with the labels that each got.

#1428 OffSpill reco changes
  CosmicReco/fcl/prolog.fcl
  DAQ/src/CaloDigiFromFragments_module.cc
  DataProducts/inc/StrawId.hh
  Mu2eKinKal/fcl/prolog.fcl
  Mu2eKinKal/inc/KKFit.hh
  Mu2eKinKal/inc/KKTrack.hh
  Mu2eKinKal/src/CentralHelixFit_module.cc
  Mu2eKinKal/src/LoopHelixFit_module.cc
  Mu2eKinKal/test/KKDrift.fcl
  Mu2eKinKal/test/KKDrift_nobkg.fcl
  Mu2eKinKal/test/KKDrift_nocalo.fcl
  Mu2eKinKal/test/KKLineDrift.fcl
  Mu2eKinKal/test/KKLineSeed.fcl
  Mu2eKinKal/test/KKOffSpill.fcl
  Mu2eKinKal/test/KKOffSpillSeed.fcl
  Mu2eKinKal/test/KKSeed.fcl
  Mu2eKinKal/test/KKSeed_nobkg.fcl
  Mu2eKinKal/test/TTTA.fcl
  Mu2eKinKal/test/TTTA_nobkg.fcl
  Print/fcl/printCaloCluster.fcl
  RecoDataProducts/inc/KalSegment.hh
  RecoDataProducts/inc/TrkFitDirection.hh
  RecoDataProducts/src/KalSeed.cc
  TrkFilters/src/KalSeedFilter_module.cc
  TrkPatRec/fcl/prolog.fcl
  TrkReco/fcl/Particle.fcl
  bin/check_cmake.sh
Labels: build failed

#1433 Update CMake targets with their Spack-compatible names
  CMakeLists.txt
  DAQ/CMakeLists.txt
  DAQ/src/CrvDigisFromFragments_module.cc
  TrackerMC/CMakeLists.txt
  Trigger/CMakeLists.txt
Labels: build finished

#1434 Renaming the DAQ modules to improve clarity + added mu2e::EventHeader to the DataDecoders maker
  DAQ/CMakeLists.txt
  DAQ/src/CRVDigisFromDataDecoders_module.cc
  DAQ/src/CaloDigisFromDataDecoders_module.cc
  DAQ/src/CaloHitsFromDataDecoders_module.cc
  DAQ/src/ComboHitsFromDataDecoders_module.cc
  DAQ/src/DataDecodersAna_module.cc
  DAQ/src/ProcessDTCAndCFOEvents_module.cc
  DAQ/src/StrawDigisFromDataDecoders_module.cc
Labels: build finished

#1427 Added calo hit integrity checks on BoardID and ChannelID
  DAQ/inc/CaloDAQUtilities.hh
Labels: build finished

#1429 MatEnv Interface Changes
  Mu2eKinKal/inc/KKStrawMaterial.hh
  Mu2eKinKal/src/KKMaterial.cc
  Mu2eKinKal/src/KKStrawMaterial.cc
Labels: build finished

#1424 CRV Global Run
  CRVReco/fcl/prolog_v11.fcl
  CRVReco/src/CrvDQMcollector_module.cc
  DAQ/CMakeLists.txt
  DAQ/src/ArtBinaryPacketsFromDigis_module.cc
  DAQ/src/CRVDigisFromDataDecoders_module.cc
  DAQ/src/CRVGlobalRunDataFromDataDecoders_module.cc
  DAQ/src/ProcessDTCAndCFOEvents_module.cc
  DAQ/test/generateCrvDigiFromFragment.fcl
  DAQ/test/generateCrvDigiFromFragment_wideband1module.fcl
  DAQ/test/generateCrvGlobalRunDataFromFragments.fcl
  EventDisplay/CMakeLists.txt
  EventDisplay/src/Cube.h
  EventDisplay/src/DataInterface.cc
  EventDisplay/src/Track.h
  RecoDataProducts/inc/DAQerror.hh
  RecoDataProducts/src/DAQerror.cc
  RecoDataProducts/src/classes.h
  RecoDataProducts/src/classes_def.xml
Labels: build running

#1436 Add example module to examine the trigger path results
  Trigger/CMakeLists.txt
  Trigger/fcl/read_trig_paths.fcl
  Trigger/src/ReadTriggerInfo_module.cc
  Trigger/src/ReadTriggerPath_module.cc
  Trigger/src/SConscript
Labels: build finished

#1441 Try to bring the build flags in to agreement with the SCons-based build
  CMakeLists.txt
Labels: build pending

#1439 Add CAPHRI digi count to lumi stream output
  CaloReco/src/CaloHitMakerFast_module.cc
  DAQ/src/CaloHitsFromDataDecoders_module.cc
  RecoDataProducts/inc/IntensityInfoCalo.hh
Labels: build finished

#1437 good run list
  DbService/CMakeLists.txt
  DbService/data/create_grl.sql
  DbService/inc/DbSql.hh
  DbService/inc/GrlBit.hh
  DbService/inc/GrlEntry.hh
  DbService/inc/GrlHeader.hh
  DbService/inc/GrlList.hh
  DbService/inc/GrlTool.hh
  DbService/inc/GrlWord.hh
  DbService/inc/RunSelect.hh
  DbService/src/DbSql.cc
  DbService/src/GrlHeader.cc
  DbService/src/GrlList.cc
  DbService/src/GrlTool.cc
  DbService/src/SConscript
  DbService/src/grlTool_main.cc
  Filters/CMakeLists.txt
  Filters/src/GoodRunFilter_module.cc
  GeneralUtilities/inc/TimeUtility.hh
  GeneralUtilities/src/TimeUtility.cc
Labels: build pending

#1443 fix accidental edit
  DbService/CMakeLists.txt
Labels: build finished

#1442 Remove otsdaq-mu2e dependency
  STMReco/CMakeLists.txt
Labels: build finished

#1444 move head to p073
  .muse
Labels: build finished

#1445 Add process dependence to lognormal PBI simulation
  EventMixing/src/ProtonBunchIntensityLogNormal_module.cc
  MCDataProducts/inc/ProcessCode.hh
  MCDataProducts/src/ProcessCode.cc
Labels: build failed

#1451 Avoid machine precision errors in acos
  Mu2eKinKal/src/KKFitUtilities.cc
Labels: build finished
